/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyscanner;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mizo_
 */
public class AdminViewStaff extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int xMouse;
    int yMouse;
    
    
    public AdminViewStaff() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitWindow = new javax.swing.JLabel();
        minimizeWindow = new javax.swing.JLabel();
        mouseDrag = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        staffNoField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        fnameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnameField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        genderField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jobTypeField = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        phoneField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        clearFields = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/Logo.png"))); // NOI18N
        jLabel1.setText("Skyscanner Admin");

        exitWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/passengerFormImages/icons8_close_window_30px.png"))); // NOI18N
        exitWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitWindowMouseEntered(evt);
            }
        });

        minimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/passengerFormImages/icons8_minimize_window_30px.png"))); // NOI18N
        minimizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseEntered(evt);
            }
        });

        mouseDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseDragMouseDragged(evt);
            }
        });
        mouseDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseDragMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(mouseDrag, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(minimizeWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitWindow))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mouseDrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 70));

        jSeparator1.setBackground(java.awt.Color.darkGray);
        jSeparator1.setForeground(java.awt.Color.darkGray);
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 10, 700));

        Table.setBackground(java.awt.Color.darkGray);
        Table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 710, 520));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("StaffNo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 10));

        staffNoField.setBackground(new java.awt.Color(102, 102, 102));
        staffNoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        staffNoField.setText("StaffNo");
        staffNoField.setBorder(null);
        jPanel1.add(staffNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 30));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 10));

        fnameField.setBackground(new java.awt.Color(102, 102, 102));
        fnameField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fnameField.setText("Fname");
        fnameField.setBorder(null);
        jPanel1.add(fnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fname:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, 30));

        lnameField.setBackground(new java.awt.Color(102, 102, 102));
        lnameField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lnameField.setText("Lname");
        lnameField.setBorder(null);
        lnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 30));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 160, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lname:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 30));

        dobField.setBackground(new java.awt.Color(102, 102, 102));
        dobField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dobField.setText("DOB");
        dobField.setBorder(null);
        jPanel1.add(dobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 160, 30));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 160, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOB:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 70, 30));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 160, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("City:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 70, 30));

        cityField.setBackground(new java.awt.Color(102, 102, 102));
        cityField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cityField.setText("City");
        cityField.setBorder(null);
        jPanel1.add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 160, 30));

        countryField.setBackground(new java.awt.Color(102, 102, 102));
        countryField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        countryField.setText("Country");
        countryField.setBorder(null);
        countryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryFieldActionPerformed(evt);
            }
        });
        jPanel1.add(countryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 160, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Country:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 70, 30));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 160, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 70, 30));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 160, 10));

        genderField.setBackground(new java.awt.Color(102, 102, 102));
        genderField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        genderField.setText("Gender");
        genderField.setBorder(null);
        jPanel1.add(genderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 160, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JobType:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 70, 30));

        jobTypeField.setBackground(new java.awt.Color(102, 102, 102));
        jobTypeField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jobTypeField.setText("JobType");
        jobTypeField.setBorder(null);
        jPanel1.add(jobTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 160, 30));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 160, 10));

        phoneField.setBackground(new java.awt.Color(102, 102, 102));
        phoneField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        phoneField.setText("PhoneNo");
        phoneField.setBorder(null);
        jPanel1.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, 160, 30));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 710, 160, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PhoneNo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 70, 30));

        clearFields.setBackground(new java.awt.Color(0, 0, 0));
        clearFields.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearFields.setForeground(new java.awt.Color(255, 255, 255));
        clearFields.setText("CLR");
        clearFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearFieldsMouseEntered(evt);
            }
        });
        jPanel1.add(clearFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 710, 130, -1));

        insertBtn.setBackground(new java.awt.Color(0, 0, 0));
        insertBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(255, 255, 255));
        insertBtn.setText("Insert");
        insertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertBtnMouseEntered(evt);
            }
        });
        jPanel1.add(insertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 130, 30));

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 710, 130, 30));

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitWindowMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
        else if (response == JOptionPane.NO_OPTION){

        }
    }//GEN-LAST:event_exitWindowMouseClicked

    private void exitWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitWindowMouseEntered
        exitWindow.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitWindowMouseEntered

    private void minimizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseClicked
        this.setExtendedState(AdminViewStaff.ICONIFIED);
    }//GEN-LAST:event_minimizeWindowMouseClicked

    private void minimizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseEntered
        minimizeWindow.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_minimizeWindowMouseEntered

    private void mouseDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse , y - yMouse);
    }//GEN-LAST:event_mouseDragMouseDragged

    private void mouseDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_mouseDragMousePressed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel)Table.getModel();
        int selectedRow = Table.getSelectedRow();
        
        staffNoField.setText(model.getValueAt(selectedRow, 0).toString());
        fnameField.setText(model.getValueAt(selectedRow, 1).toString());
        lnameField.setText(model.getValueAt(selectedRow, 2).toString());
        dobField.setText(model.getValueAt(selectedRow, 3).toString());
        cityField.setText(model.getValueAt(selectedRow, 4).toString());
        countryField.setText(model.getValueAt(selectedRow, 5).toString());
        genderField.setText(model.getValueAt(selectedRow, 6).toString());
        jobTypeField.setText(model.getValueAt(selectedRow, 7).toString());
        phoneField.setText(model.getValueAt(selectedRow, 8).toString());
        
    }//GEN-LAST:event_TableMouseClicked

    private void lnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameFieldActionPerformed

    private void countryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFieldActionPerformed

    private void clearFieldsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldsMouseClicked
        staffNoField.setText("");
        fnameField.setText("");
        lnameField.setText("");
        dobField.setText("");
        cityField.setText("");
        countryField.setText("");
        genderField.setText("");
        jobTypeField.setText("");
        phoneField.setText("");
    }//GEN-LAST:event_clearFieldsMouseClicked

    private void clearFieldsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldsMouseEntered
        clearFields.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_clearFieldsMouseEntered

    private void insertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseClicked
        if (staffNoField.getText().isBlank() == true || fnameField.getText().isBlank() == true|| lnameField.getText().isBlank() == true
            || dobField.getText().isBlank() == true || cityField.getText().isBlank() == true || countryField.getText().isBlank() == true
            || genderField.getText().isBlank() == true || jobTypeField.getText().isBlank() == true ||  phoneField.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Some data fields are empty"
                , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                String sql = "INSERT INTO `staff`(`StaffNo`, `Fname`, `Lname`, `DOB`, `City`, `Country`, `Gender`, `Job_Type`) VALUES (?,?,?,?,?,?,?,?)";
                con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
                pst = con.prepareStatement(sql);
                pst.setString(1, staffNoField.getText());
                pst.setString(2, fnameField.getText());
                pst.setString(3, lnameField.getText());
                pst.setString(4, dobField.getText());
                pst.setString(5, cityField.getText());
                pst.setString(6, countryField.getText());
                pst.setString(7, genderField.getText());
                pst.setString(8, jobTypeField.getText());
                pst.executeUpdate();

                String sql2 = "INSERT INTO `staff_phone`(`StaffNo`, `PhoneNo`) VALUES (?,?)";
                pst = con.prepareStatement(sql2);
                pst.setString(1, staffNoField.getText());
                pst.setString(2, phoneField.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null , "Data inserted successfully");

            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Error in inserting data , StaffNo" , "ERROR" , JOptionPane.ERROR_MESSAGE);
            }
            showTableData();
        }
    }//GEN-LAST:event_insertBtnMouseClicked

    private void insertBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseEntered
        insertBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_insertBtnMouseEntered

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        if (fnameField.getText().isBlank() == true|| lnameField.getText().isBlank() == true|| dobField.getText().isBlank() == true || 
                cityField.getText().isBlank() == true || countryField.getText().isBlank() == true
            || genderField.getText().isBlank() == true || jobTypeField.getText().isBlank() == true ||  phoneField.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Some fields are empty excluding StaffNo field" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {
            String sql = "UPDATE `staff` SET `Fname`= ?,`Lname`=?,`DOB`=?,`City`=?,`Country`=?,`Gender`=?,`Job_Type`= ? WHERE StaffNo = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1, fnameField.getText());
            pst.setString(2, lnameField.getText());
            pst.setString(3, dobField.getText());
            pst.setString(4, cityField.getText());
            pst.setString(5, countryField.getText());
            pst.setString(6, genderField.getText());
            pst.setString(7, jobTypeField.getText());
            pst.setString(8, staffNoField.getText());
            pst.executeUpdate();

            
            String sql2 = "UPDATE `staff_phone` SET `PhoneNo`= ? WHERE staff_phone.StaffNo = ?";
            pst = con.prepareStatement(sql2);
            pst.setString(1, phoneField.getText());
            pst.setString(2, staffNoField.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null , "Data updated successfully");

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error in updating data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        if (staffNoField.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Staff Number field must be filled to delete data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {
            String sql = "DELETE FROM staff WHERE StaffNo = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1, staffNoField.getText());
            pst.executeUpdate();

            String sql2 = "DELETE FROM `staff_phone` WHERE StaffNo = ?";
            pst = con.prepareStatement(sql2);
            pst.setString(1, staffNoField.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null , "Data deleted successfully");

        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in deleting data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteBtnMouseEntered

    public void showTableData(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            String sql = "select staff.StaffNo , staff.Fname , staff.Lname , staff.DOB , staff.City , staff.Country , staff.Gender , staff.Job_Type , staff_phone.PhoneNo from staff\n" +
"join staff_phone on staff.StaffNo = staff_phone.StaffNo\n" +
"where Job_Type <>'ADMIN';";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in displaying data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
          }
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField cityField;
    private javax.swing.JButton clearFields;
    private javax.swing.JTextField countryField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel exitWindow;
    private javax.swing.JTextField fnameField;
    private javax.swing.JTextField genderField;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jobTypeField;
    private javax.swing.JTextField lnameField;
    private javax.swing.JLabel minimizeWindow;
    private javax.swing.JLabel mouseDrag;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField staffNoField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
