/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyscanner;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mizo_
 */
public class AdminViewTickets extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    int xMouse;
    int yMouse;

    public AdminViewTickets() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitWindow = new javax.swing.JLabel();
        minimizeWindow = new javax.swing.JLabel();
        mouseDrag = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        clearFields = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ticketNoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        departureField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        bookingField = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        passportNoField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        adminNoField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/Logo.png"))); // NOI18N
        jLabel1.setText("Skyscanner Admin");

        exitWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/passengerFormImages/icons8_close_window_30px.png"))); // NOI18N
        exitWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitWindowMouseEntered(evt);
            }
        });

        minimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/passengerFormImages/icons8_minimize_window_30px.png"))); // NOI18N
        minimizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseEntered(evt);
            }
        });

        mouseDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseDragMouseDragged(evt);
            }
        });
        mouseDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseDragMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(mouseDrag, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(minimizeWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitWindow)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mouseDrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 70));

        Table.setBackground(java.awt.Color.darkGray);
        Table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 510, 480));

        jSeparator1.setBackground(java.awt.Color.darkGray);
        jSeparator1.setForeground(java.awt.Color.darkGray);
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 10, 700));

        clearFields.setBackground(new java.awt.Color(0, 0, 0));
        clearFields.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearFields.setForeground(new java.awt.Color(255, 255, 255));
        clearFields.setText("CLR");
        clearFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearFieldsMouseEntered(evt);
            }
        });
        jPanel1.add(clearFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, 100, -1));

        insertBtn.setBackground(new java.awt.Color(0, 0, 0));
        insertBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(255, 255, 255));
        insertBtn.setText("Insert");
        insertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertBtnMouseEntered(evt);
            }
        });
        jPanel1.add(insertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 700, 100, 30));

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 700, 90, 30));

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 700, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TicketNo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, 10));

        ticketNoField.setBackground(new java.awt.Color(102, 102, 102));
        ticketNoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ticketNoField.setText("TicketNo");
        ticketNoField.setBorder(null);
        jPanel1.add(ticketNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 50, 30));

        departureField.setBackground(new java.awt.Color(102, 102, 102));
        departureField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        departureField.setText("Type");
        departureField.setBorder(null);
        jPanel1.add(departureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 160, 30));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 160, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 50, 30));

        statusField.setBackground(new java.awt.Color(102, 102, 102));
        statusField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        statusField.setText("ReservationStatus");
        statusField.setBorder(null);
        jPanel1.add(statusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 160, 30));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 160, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BookingID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 80, 30));

        bookingField.setBackground(new java.awt.Color(102, 102, 102));
        bookingField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingField.setText("BookingID");
        bookingField.setBorder(null);
        jPanel1.add(bookingField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 150, 30));

        jSeparator13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 160, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PassportNo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 90, 30));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 160, 10));

        passportNoField.setBackground(new java.awt.Color(102, 102, 102));
        passportNoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passportNoField.setText("PassportNo");
        passportNoField.setBorder(null);
        jPanel1.add(passportNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 160, 30));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 160, 10));

        adminNoField.setBackground(new java.awt.Color(102, 102, 102));
        adminNoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        adminNoField.setText("AdminNo");
        adminNoField.setBorder(null);
        jPanel1.add(adminNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AdminNo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitWindowMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
        else if (response == JOptionPane.NO_OPTION){

        }
    }//GEN-LAST:event_exitWindowMouseClicked

    private void exitWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitWindowMouseEntered
        exitWindow.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitWindowMouseEntered

    private void minimizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseClicked
        this.setExtendedState(AdminViewTickets.ICONIFIED);
    }//GEN-LAST:event_minimizeWindowMouseClicked

    private void minimizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseEntered
        minimizeWindow.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_minimizeWindowMouseEntered

    private void mouseDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse , y - yMouse);
    }//GEN-LAST:event_mouseDragMouseDragged

    private void mouseDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_mouseDragMousePressed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel)Table.getModel();
        int selectedRow = Table.getSelectedRow();
        ticketNoField.setText(model.getValueAt(selectedRow, 0).toString());
        departureField.setText(model.getValueAt(selectedRow, 1).toString());
        statusField.setText(model.getValueAt(selectedRow, 2).toString());
        bookingField.setText(model.getValueAt(selectedRow, 3).toString());
        adminNoField.setText(model.getValueAt(selectedRow, 5).toString());
        try{
        passportNoField.setText(model.getValueAt(selectedRow, 4).toString());
        }
        catch (Exception ex){
        }

        
    }//GEN-LAST:event_TableMouseClicked

    private void clearFieldsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldsMouseClicked

        ticketNoField.setText("");
        departureField.setText("");
        statusField.setText("");
        bookingField.setText("");
        passportNoField.setText("");
        adminNoField.setText("");
        
    }//GEN-LAST:event_clearFieldsMouseClicked

    private void clearFieldsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldsMouseEntered
        clearFields.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_clearFieldsMouseEntered

    private void insertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseClicked

        if (ticketNoField.getText().isBlank() == true || departureField.getText().isBlank() || statusField.getText().isBlank() || bookingField.getText().isBlank()
                || adminNoField.getText().isBlank()){
             JOptionPane.showMessageDialog(null, "Some data fields are empty", "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {          
            String sql = "INSERT INTO `tickets`(`TicketNo`, `Type`, `Reservation_Status`, `BookingID`, `AdminNo`) VALUES (?,?,?,?,?)"; 
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1, ticketNoField.getText());
            pst.setString(2, departureField.getText());
            pst.setString(3, statusField.getText());
            pst.setString(4, bookingField.getText());
            pst.setString(5, adminNoField.getText());
            pst.executeUpdate();
            
                       
            JOptionPane.showMessageDialog(null , "Data inserted successfully");
            
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in inserting data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();
        }
        
    }//GEN-LAST:event_insertBtnMouseClicked

    private void insertBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseEntered
        insertBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_insertBtnMouseEntered

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (departureField.getText().isBlank() == true  || statusField.getText().isBlank() == true || passportNoField.getText().isBlank() == true || 
               adminNoField.getText().isBlank() == true || ticketNoField.getText().isBlank() == true ){
             JOptionPane.showMessageDialog(null, "Some data fields are empty , please fill them and retry" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        
        
        try {
        String sql = "UPDATE `tickets` SET `Type`= ? ,`Reservation_Status`= ? ,`PassportNo`= ? ,`AdminNo`= ? WHERE TicketNo = ?";
        con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
        pst = con.prepareStatement(sql);
        pst.setString(1, departureField.getText());
        pst.setString(2, statusField.getText());
        pst.setString(3, passportNoField.getText());
        pst.setString(4, adminNoField.getText());
        pst.setString(5, ticketNoField.getText());
        pst.executeUpdate();
        
        
        
        JOptionPane.showMessageDialog(null , "Data updated successfully");
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error in updating data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();
        

    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        if (ticketNoField.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Ticket Number field is empty , it must be filled to delete ticket" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        try {
            String sql = "DELETE FROM tickets where TicketNo = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1, ticketNoField.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null , "Data deleted successfully");
            
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in deleting data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();

    }//GEN-LAST:event_deleteBtnMouseClicked

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteBtnMouseEntered

    public void showTableData(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            String sql = "SELECT * FROM `tickets`";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in displaying data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
          }
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField adminNoField;
    private javax.swing.JTextField bookingField;
    private javax.swing.JButton clearFields;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField departureField;
    private javax.swing.JLabel exitWindow;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel minimizeWindow;
    private javax.swing.JLabel mouseDrag;
    private javax.swing.JTextField passportNoField;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextField ticketNoField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
