/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyscanner;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mizo_
 */
public class AdminViewFlights extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int xMouse;
    int yMouse;
    
    
    public AdminViewFlights() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitWindow = new javax.swing.JLabel();
        minimizeWindow = new javax.swing.JLabel();
        mouseDrag = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        flightNoField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        departureField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        arrivalField = new javax.swing.JTextField();
        departureCityField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        arrivalCityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        flightDateField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        directIndirectField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        airlineNameField = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        clearFields = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        scheduleIDField = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        airlineCodeField = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        flightDurationField = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/Logo.png"))); // NOI18N
        jLabel1.setText("Skyscanner Admin");

        exitWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/passengerFormImages/icons8_close_window_30px.png"))); // NOI18N
        exitWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitWindowMouseEntered(evt);
            }
        });

        minimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/passengerFormImages/icons8_minimize_window_30px.png"))); // NOI18N
        minimizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseEntered(evt);
            }
        });

        mouseDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseDragMouseDragged(evt);
            }
        });
        mouseDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseDragMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(mouseDrag, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(minimizeWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitWindow))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mouseDrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 70));

        jSeparator1.setBackground(java.awt.Color.darkGray);
        jSeparator1.setForeground(java.awt.Color.darkGray);
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 10, 700));

        Table.setBackground(java.awt.Color.darkGray);
        Table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 680, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FlightNo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 30));

        flightNoField.setBackground(new java.awt.Color(102, 102, 102));
        flightNoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        flightNoField.setText("FlightNo");
        flightNoField.setBorder(null);
        jPanel1.add(flightNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 160, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Departure:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 30));

        departureField.setBackground(new java.awt.Color(102, 102, 102));
        departureField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        departureField.setText("Departure");
        departureField.setBorder(null);
        jPanel1.add(departureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 30));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, 10));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 160, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Arrival:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 60, 30));

        arrivalField.setBackground(new java.awt.Color(102, 102, 102));
        arrivalField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        arrivalField.setText("Arrival");
        arrivalField.setBorder(null);
        jPanel1.add(arrivalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 160, 30));

        departureCityField.setBackground(new java.awt.Color(102, 102, 102));
        departureCityField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        departureCityField.setText("DepartureCity");
        departureCityField.setBorder(null);
        jPanel1.add(departureCityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FlightDuration:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 30));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 160, 10));

        arrivalCityField.setBackground(new java.awt.Color(102, 102, 102));
        arrivalCityField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        arrivalCityField.setText("ArrivalCity");
        arrivalCityField.setBorder(null);
        jPanel1.add(arrivalCityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ArrivalCity:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 80, 30));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 160, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FlightDate:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 80, 30));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 160, 10));

        flightDateField.setBackground(new java.awt.Color(102, 102, 102));
        flightDateField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        flightDateField.setText("FlightDate");
        flightDateField.setBorder(null);
        jPanel1.add(flightDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 160, 30));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 160, 10));

        directIndirectField.setBackground(new java.awt.Color(102, 102, 102));
        directIndirectField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        directIndirectField.setText("Direct or Indirect");
        directIndirectField.setBorder(null);
        jPanel1.add(directIndirectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 160, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AirlineCode:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, 30));

        airlineNameField.setBackground(new java.awt.Color(102, 102, 102));
        airlineNameField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        airlineNameField.setText("AirlineName");
        airlineNameField.setBorder(null);
        airlineNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(airlineNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, 160, 30));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, 160, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("AirlineName:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 90, 30));

        priceField.setBackground(new java.awt.Color(102, 102, 102));
        priceField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        priceField.setText("Price");
        priceField.setBorder(null);
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });
        jPanel1.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, 160, 30));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 740, 160, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, 50, 30));

        clearFields.setBackground(new java.awt.Color(0, 0, 0));
        clearFields.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearFields.setForeground(new java.awt.Color(255, 255, 255));
        clearFields.setText("CLR");
        clearFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearFieldsMouseEntered(evt);
            }
        });
        jPanel1.add(clearFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 710, 130, -1));

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, 130, 30));

        insertBtn.setBackground(new java.awt.Color(0, 0, 0));
        insertBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(255, 255, 255));
        insertBtn.setText("Insert");
        insertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertBtnMouseEntered(evt);
            }
        });
        jPanel1.add(insertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 130, 30));

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 710, 130, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DepartureCity:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Direct/Indirect:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ScheduleID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, 30));

        scheduleIDField.setBackground(new java.awt.Color(102, 102, 102));
        scheduleIDField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        scheduleIDField.setText("ScheduleID");
        scheduleIDField.setBorder(null);
        jPanel1.add(scheduleIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 150, 30));

        jSeparator11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 160, 10));

        airlineCodeField.setBackground(new java.awt.Color(102, 102, 102));
        airlineCodeField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        airlineCodeField.setText("AirlineCode");
        airlineCodeField.setBorder(null);
        airlineCodeField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airlineCodeFieldMouseClicked(evt);
            }
        });
        jPanel1.add(airlineCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 150, 30));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 160, 10));

        flightDurationField.setBackground(new java.awt.Color(102, 102, 102));
        flightDurationField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        flightDurationField.setText("FlightDuration");
        flightDurationField.setBorder(null);
        jPanel1.add(flightDurationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 30));

        jSeparator13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 160, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitWindowMouseEntered
        exitWindow.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitWindowMouseEntered

    private void exitWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitWindowMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
        else if (response == JOptionPane.NO_OPTION){
            
        }
    }//GEN-LAST:event_exitWindowMouseClicked

    private void minimizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseEntered
        minimizeWindow.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_minimizeWindowMouseEntered

    private void minimizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseClicked
        this.setExtendedState(AdminViewFlights.ICONIFIED);
    }//GEN-LAST:event_minimizeWindowMouseClicked

    private void mouseDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_mouseDragMousePressed

    private void mouseDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse , y - yMouse);
    }//GEN-LAST:event_mouseDragMouseDragged

    private void airlineNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlineNameFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel)Table.getModel();
        int selectedRow = Table.getSelectedRow();
        
        flightNoField.setText(model.getValueAt(selectedRow, 0).toString());
        departureField.setText(model.getValueAt(selectedRow, 1).toString());
        arrivalField.setText(model.getValueAt(selectedRow, 2).toString());
        flightDurationField.setText(model.getValueAt(selectedRow, 3).toString());
        departureCityField.setText(model.getValueAt(selectedRow, 4).toString());
        arrivalCityField.setText(model.getValueAt(selectedRow, 5).toString());
        flightDateField.setText(model.getValueAt(selectedRow, 6).toString());
        directIndirectField.setText(model.getValueAt(selectedRow, 7).toString());
        scheduleIDField.setText(model.getValueAt(selectedRow, 8).toString());
        airlineCodeField.setText(model.getValueAt(selectedRow, 9).toString());
        airlineNameField.setText(model.getValueAt(selectedRow, 10).toString());
        priceField.setText(model.getValueAt(selectedRow, 11).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void clearFieldsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldsMouseEntered
        clearFields.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_clearFieldsMouseEntered

    private void clearFieldsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldsMouseClicked
        flightNoField.setText("");
        departureField.setText("");
        arrivalField.setText("");
        departureCityField.setText("");
        arrivalCityField.setText("");
        flightDateField.setText("");
        directIndirectField.setText("");
        airlineNameField.setText("");
        priceField.setText("");
        flightDurationField.setText("");
        scheduleIDField.setText("");
        airlineCodeField.setText("");
    }//GEN-LAST:event_clearFieldsMouseClicked

    private void insertBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseEntered
        insertBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_insertBtnMouseEntered

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (priceField.getText().isBlank() == true || flightDurationField.getText().isBlank() == true || arrivalField.getText().isBlank() == true || 
                departureField.getText().isBlank() == true || directIndirectField.getText().isBlank() == true || departureCityField.getText().isBlank() == true
                || arrivalCityField.getText().isBlank() == true || flightNoField.getText().isBlank() == true || flightDateField.getText().isBlank() == true ||
                        scheduleIDField.getText().isBlank() == true || airlineCodeField.getText().isBlank() == true || flightNoField.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Some fields are empty , please fill all fields and retry" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {
        String sql = "UPDATE `flight` SET `Price`= ? ,`Flight_Duration`= ? ,`Arrival`= ? ,`Departure`= ? ,`Direct_Indirect`= ? , `Departure_City`= ? ,`Arrival_City`= ? WHERE FlightNo = ?";
        con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
        pst = con.prepareStatement(sql);
        pst.setString(1, priceField.getText());
        pst.setString(2, flightDurationField.getText());
        pst.setString(3, arrivalField.getText());
        pst.setString(4, departureField.getText());
        pst.setString(5, directIndirectField.getText());
        pst.setString(6, departureCityField.getText());
        pst.setString(7, arrivalCityField.getText());
        pst.setString(8, flightNoField.getText());
        pst.executeUpdate();
        
        String sql2 = "UPDATE `flightschedule` SET `Flight_Date`= ? WHERE ScheduleID = ?";
        pst = con.prepareStatement(sql2);
        pst.setString(1, flightDateField.getText());
        pst.setString(2, scheduleIDField.getText());
        pst.executeUpdate();
        
        String sql3 = "UPDATE `flight` SET AirlineCode = ? WHERE FlightNo = ?";
        pst = con.prepareStatement(sql3);
        pst.setString(1, airlineCodeField.getText());
        pst.setString(2, flightNoField.getText());
        pst.executeUpdate();
        
        
        JOptionPane.showMessageDialog(null , "Data updated successfully");
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error in updating data , Data being updated must follow DB constraints" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void airlineCodeFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airlineCodeFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_airlineCodeFieldMouseClicked

    private void insertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseClicked
        if (flightNoField.getText().isBlank() == true || departureField.getText().isBlank() == true|| arrivalField.getText().isBlank() == true
                || flightDurationField.getText().isBlank() == true || departureCityField.getText().isBlank() == true || arrivalCityField.getText().isBlank() == true
                || flightDateField.getText().isBlank() == true || directIndirectField.getText().isBlank() == true ||  scheduleIDField.getText().isBlank() == true||
                airlineCodeField.getText().isBlank() == true || priceField.getText().isBlank() == true || airlineNameField.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Some data fields are empty"
                    , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {
            String sql3 = "INSERT INTO `flightschedule`(`ScheduleID`, `Flight_Date`) VALUES (?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            pst = con.prepareStatement(sql3);
            pst.setString(1, scheduleIDField.getText());
            pst.setString(2, flightDateField.getText());
            pst.executeUpdate();
              
            String sql = "INSERT INTO `flight`(`FlightNo`, `Price`, `Flight_Duration`, `Arrival`, `Departure`, `Direct_Indirect`, `AirlineCode`, `ScheduleID`, `Departure_City`, `Arrival_City`) VALUES (?,?,?,?,?,?,?,?,?,?)"; 
            pst = con.prepareStatement(sql);
            pst.setString(1, flightNoField.getText());
            pst.setString(2, priceField.getText());
            pst.setString(3, flightDurationField.getText());
            pst.setString(4, arrivalField.getText());
            pst.setString(5, departureField.getText());
            pst.setString(6, directIndirectField.getText());
            pst.setString(7, airlineCodeField.getText());
            pst.setString(8, scheduleIDField.getText());
            pst.setString(9, departureCityField.getText());
            pst.setString(10, arrivalCityField.getText());
            pst.executeUpdate();
                       
            
            JOptionPane.showMessageDialog(null , "Data inserted successfully");
            
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in inserting data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();
        }
    }//GEN-LAST:event_insertBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        if (flightNoField.getText().isBlank() == true || scheduleIDField.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Flight Number field and scheduleID field cannot be empty to delete data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {
            String sql = "DELETE FROM flight WHERE FlightNo = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1, flightNoField.getText());
            pst.executeUpdate();
            
            String sql2 = "DELETE FROM flightschedule WHERE ScheduleID = ?";
            pst = con.prepareStatement(sql2);
            pst.setString(1, scheduleIDField.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null , "Data deleted successfully");
            
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in deleting data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        showTableData();
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    
    public void showTableData(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner","root","");
            String sql = "SELECT flight.FlightNo , flight.Departure , flight.Arrival, flight.Flight_Duration ,flight.Departure_City , flight.Arrival_City ,flightschedule.Flight_Date , flight.Direct_Indirect , flight.ScheduleID , flight.AirlineCode , airline.AirlineName , flight.Price from flight inner join airline on flight.AirlineCode = airline.AirlineCode inner join flightschedule on flight.ScheduleID = flightschedule.ScheduleID";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error in displaying data" , "ERROR" , JOptionPane.ERROR_MESSAGE);
          }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewFlights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField airlineCodeField;
    private javax.swing.JTextField airlineNameField;
    private javax.swing.JTextField arrivalCityField;
    private javax.swing.JTextField arrivalField;
    private javax.swing.JButton clearFields;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField departureCityField;
    private javax.swing.JTextField departureField;
    private javax.swing.JTextField directIndirectField;
    private javax.swing.JLabel exitWindow;
    private javax.swing.JTextField flightDateField;
    private javax.swing.JTextField flightDurationField;
    private javax.swing.JTextField flightNoField;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel minimizeWindow;
    private javax.swing.JLabel mouseDrag;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField scheduleIDField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
