/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyscanner;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.regex.*;


public class passengerForgotPassword extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    static int attemptForgotPassenger = 1;
    
    public passengerForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backPassengerForgot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passportNoInput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        recoverPasswordBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));

        backPassengerForgot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/icons8_back_arrow_40px.png"))); // NOI18N
        backPassengerForgot.setBorder(null);
        backPassengerForgot.setContentAreaFilled(false);
        backPassengerForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backPassengerForgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backPassengerForgotMouseEntered(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(186, 79, 84));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(186, 79, 84));
        jLabel1.setText("Passenger Password Recovery");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/StaffNo_Img.png"))); // NOI18N

        passportNoInput.setBackground(new java.awt.Color(74, 31, 61));
        passportNoInput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passportNoInput.setForeground(new java.awt.Color(204, 204, 204));
        passportNoInput.setText("Passport Number");
        passportNoInput.setBorder(null);
        passportNoInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passportNoInputFocusGained(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/User_icon.png"))); // NOI18N

        usernameInput.setBackground(new java.awt.Color(74, 31, 61));
        usernameInput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernameInput.setForeground(new java.awt.Color(204, 204, 204));
        usernameInput.setText("Username");
        usernameInput.setBorder(null);
        usernameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameInputFocusGained(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/icons8_gmail_40px.png"))); // NOI18N

        emailInput.setBackground(new java.awt.Color(74, 31, 61));
        emailInput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailInput.setForeground(new java.awt.Color(204, 204, 204));
        emailInput.setText("Email");
        emailInput.setBorder(null);
        emailInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailInputFocusGained(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        recoverPasswordBtn.setBackground(new java.awt.Color(186, 79, 84));
        recoverPasswordBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        recoverPasswordBtn.setText("Recover Password");
        recoverPasswordBtn.setBorder(null);
        recoverPasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recoverPasswordBtnMouseEntered(evt);
            }
        });
        recoverPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoverPasswordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backPassengerForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recoverPasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator1)
                        .addComponent(passportNoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(usernameInput)
                        .addComponent(emailInput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backPassengerForgot, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passportNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(usernameInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(recoverPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backPassengerForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backPassengerForgotMouseEntered
       backPassengerForgot.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backPassengerForgotMouseEntered

    private void backPassengerForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backPassengerForgotMouseClicked
        passengerLogin passengerLogin1 = new passengerLogin();
        passengerLogin1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backPassengerForgotMouseClicked

    private void passportNoInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passportNoInputFocusGained
        passportNoInput.setText("");
    }//GEN-LAST:event_passportNoInputFocusGained

    private void usernameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFocusGained
        usernameInput.setText("");
    }//GEN-LAST:event_usernameInputFocusGained

    private void emailInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInputFocusGained
        emailInput.setText("");
    }//GEN-LAST:event_emailInputFocusGained

    private void recoverPasswordBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recoverPasswordBtnMouseEntered
        recoverPasswordBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_recoverPasswordBtnMouseEntered

    private void recoverPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoverPasswordBtnActionPerformed

        String regex = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$";
        Pattern pattern = Pattern.compile(regex);
        Matcher match = pattern.matcher(emailInput.getText());
        if (!match.matches() && emailInput.getText().isEmpty() == false){
            JOptionPane.showMessageDialog(null, "Incorrect email format , Please enter a valid email", "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        if(passportNoInput.getText().isBlank() == true && usernameInput.getText().isBlank() == true || emailInput.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Some Fields are empty, please fill them and retry", "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
            String email = emailInput.getText();
            try{
                String query = "SELECT passenger.PassportNo , passenger.Username, passenger.Password , passenger_contact.Email FROM `passenger`\n" +
                                "inner join passenger_contact on passenger.PassportNo = passenger_contact.PassportNo\n" +
                                "WHERE passenger.PassportNo = ? and passenger.Username = ? and passenger_contact.Email = ?";
                con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner" , "root" , "");
                pst = con.prepareStatement(query);
                pst.setString(1 , passportNoInput.getText());
                pst.setString(2 , usernameInput.getText());
                pst.setString(3 , email);
                rs = pst.executeQuery();
                if (rs.next()){
                    JOptionPane.showMessageDialog(this , "Password recovered:"+" "+rs.getString(3));
                }
                else{
                    JOptionPane.showMessageDialog(this, "Incorrect username or password \n Attempt: "+attemptForgotPassenger+"/3");
                    attemptForgotPassenger++;
                }
                if (attemptForgotPassenger == 4){
                    JOptionPane.showMessageDialog(this , "Maximum number of attempts reached , please try again later" , "ERROR" , JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
                
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Couldn't connect to Database , please recheck connection" , "ERROR" , JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_recoverPasswordBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passengerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passengerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passengerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passengerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passengerForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPassengerForgot;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField passportNoInput;
    private javax.swing.JButton recoverPasswordBtn;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
