/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyscanner;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class passengerLogin extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int xMouse;
    int yMouse;
    
    static int attemptPassenger = 1;
    
    
    public passengerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        passengerLoginBackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mouseDrag1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        passengerExitBtn = new javax.swing.JButton();
        passengerMinimizeBtn = new javax.swing.JButton();
        mouseDrag2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passengerUserInput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        passengerPasswordInput = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        passengerLoginBtn = new javax.swing.JButton();
        forgotPasswordBtn = new javax.swing.JButton();
        registerPassengerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));
        jPanel2.setPreferredSize(new java.awt.Dimension(395, 507));

        passengerLoginBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/icons8_back_arrow_40px.png"))); // NOI18N
        passengerLoginBackBtn.setBorder(null);
        passengerLoginBackBtn.setContentAreaFilled(false);
        passengerLoginBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengerLoginBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passengerLoginBackBtnMouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/icons8_passenger_125px.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(186, 79, 84));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(186, 79, 84));
        jLabel2.setText("Passenger Login");
        jLabel2.setMaximumSize(new java.awt.Dimension(187, 26));
        jLabel2.setMinimumSize(new java.awt.Dimension(187, 26));
        jLabel2.setPreferredSize(new java.awt.Dimension(187, 26));

        mouseDrag1.setBackground(new java.awt.Color(74, 31, 61));
        mouseDrag1.setForeground(new java.awt.Color(74, 31, 61));
        mouseDrag1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseDrag1MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(passengerLoginBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(mouseDrag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passengerLoginBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(mouseDrag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));

        passengerExitBtn.setBackground(new java.awt.Color(186, 79, 84));
        passengerExitBtn.setForeground(new java.awt.Color(74, 31, 61));
        passengerExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/ExitWindow.png"))); // NOI18N
        passengerExitBtn.setBorder(null);
        passengerExitBtn.setContentAreaFilled(false);
        passengerExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengerExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passengerExitBtnMouseEntered(evt);
            }
        });

        passengerMinimizeBtn.setBackground(new java.awt.Color(186, 79, 84));
        passengerMinimizeBtn.setForeground(new java.awt.Color(74, 31, 61));
        passengerMinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/Minimize.png"))); // NOI18N
        passengerMinimizeBtn.setBorder(null);
        passengerMinimizeBtn.setContentAreaFilled(false);
        passengerMinimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengerMinimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passengerMinimizeBtnMouseEntered(evt);
            }
        });

        mouseDrag2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseDrag2MouseDragged(evt);
            }
        });
        mouseDrag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseDrag2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/User_icon.png"))); // NOI18N

        passengerUserInput.setBackground(new java.awt.Color(186, 79, 84));
        passengerUserInput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passengerUserInput.setForeground(new java.awt.Color(204, 204, 204));
        passengerUserInput.setText("Username");
        passengerUserInput.setBorder(null);
        passengerUserInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passengerUserInputFocusGained(evt);
            }
        });
        passengerUserInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerUserInputActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyscanner/Password_icon.png"))); // NOI18N

        passengerPasswordInput.setBackground(new java.awt.Color(186, 79, 84));
        passengerPasswordInput.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passengerPasswordInput.setForeground(new java.awt.Color(204, 204, 204));
        passengerPasswordInput.setText("Password");
        passengerPasswordInput.setBorder(null);
        passengerPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passengerPasswordInputFocusGained(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        passengerLoginBtn.setBackground(new java.awt.Color(74, 31, 61));
        passengerLoginBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passengerLoginBtn.setText("Login");
        passengerLoginBtn.setBorder(null);
        passengerLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passengerLoginBtnMouseEntered(evt);
            }
        });
        passengerLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerLoginBtnActionPerformed(evt);
            }
        });

        forgotPasswordBtn.setBackground(new java.awt.Color(186, 79, 84));
        forgotPasswordBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forgotPasswordBtn.setText("Forgot Password?");
        forgotPasswordBtn.setBorder(null);
        forgotPasswordBtn.setBorderPainted(false);
        forgotPasswordBtn.setContentAreaFilled(false);
        forgotPasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPasswordBtnMouseEntered(evt);
            }
        });
        forgotPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordBtnActionPerformed(evt);
            }
        });

        registerPassengerBtn.setBackground(new java.awt.Color(74, 31, 61));
        registerPassengerBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        registerPassengerBtn.setText("Register");
        registerPassengerBtn.setBorder(null);
        registerPassengerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerPassengerBtnMouseEntered(evt);
            }
        });
        registerPassengerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPassengerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mouseDrag2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passengerMinimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passengerUserInput)
                                    .addComponent(jSeparator1)
                                    .addComponent(passengerPasswordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(jSeparator2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(passengerLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(forgotPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passengerExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(registerPassengerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mouseDrag2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengerMinimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengerExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(passengerUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(passengerPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgotPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(registerPassengerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passengerLoginBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerLoginBackBtnMouseEntered
        passengerLoginBackBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_passengerLoginBackBtnMouseEntered

    private void passengerLoginBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerLoginBackBtnMouseClicked
        Homepage home = new Homepage();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_passengerLoginBackBtnMouseClicked

    private void passengerExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerExitBtnMouseEntered
        passengerExitBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_passengerExitBtnMouseEntered

    private void passengerExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerExitBtnMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else if (response == JOptionPane.NO_OPTION){
            
        }
    }//GEN-LAST:event_passengerExitBtnMouseClicked

    private void passengerMinimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerMinimizeBtnMouseEntered
        passengerMinimizeBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_passengerMinimizeBtnMouseEntered

    private void passengerMinimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerMinimizeBtnMouseClicked
        this.setExtendedState(passengerLogin.ICONIFIED);
    }//GEN-LAST:event_passengerMinimizeBtnMouseClicked

    private void mouseDrag1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDrag1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse , y - yMouse);
    }//GEN-LAST:event_mouseDrag1MouseDragged

    private void mouseDrag2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDrag2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_mouseDrag2MousePressed

    private void mouseDrag2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDrag2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse , y - yMouse);
    }//GEN-LAST:event_mouseDrag2MouseDragged

    private void passengerUserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerUserInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengerUserInputActionPerformed

    private void passengerUserInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passengerUserInputFocusGained
        passengerUserInput.setText("");
    }//GEN-LAST:event_passengerUserInputFocusGained

    private void passengerPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passengerPasswordInputFocusGained
        passengerPasswordInput.setText("");
    }//GEN-LAST:event_passengerPasswordInputFocusGained

    private void passengerLoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerLoginBtnMouseEntered
        passengerLoginBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_passengerLoginBtnMouseEntered

    private void forgotPasswordBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordBtnMouseEntered
        forgotPasswordBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_forgotPasswordBtnMouseEntered

    private void registerPassengerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPassengerBtnMouseEntered
        registerPassengerBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_registerPassengerBtnMouseEntered

    private void passengerLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerLoginBtnActionPerformed
        if (passengerUserInput.getText().isBlank() == true && passengerPasswordInput.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Username and password fields are both empty, please fill them and retry", "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else if (passengerUserInput.getText().isBlank() == true && passengerPasswordInput.getText().isBlank() == false){
            JOptionPane.showMessageDialog(null, "Username field is empty, please fill it and retry", "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else if(passengerUserInput.getText().isBlank() == false && passengerPasswordInput.getText().isBlank() == true){
            JOptionPane.showMessageDialog(null, "Password field is empty, please fill it and retry", "ERROR" , JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String query = "SELECT * FROM `passenger` WHERE Username = ? and Password = ?";
                con = DriverManager.getConnection("jdbc:mysql://localhost/skyscanner" , "root" , "");
                pst = con.prepareStatement(query);
                pst.setString(1 , passengerUserInput.getText());
                pst.setString(2 , passengerPasswordInput.getText());
                rs = pst.executeQuery();
                if (rs.next()){
                    JOptionPane.showMessageDialog(this , "Welcome, "+" "+rs.getString(2));
                    PassengerForm passenger = new PassengerForm();
                    passenger.displayPassengerName(rs.getString(2));
                    passenger.getPassportNo(rs.getString(1));
                    passenger.setVisible(true);
                    this.setVisible(false);
                    attemptPassenger = 1;
                }
                else{
                    JOptionPane.showMessageDialog(this, "Incorrect username or password \n Attempt: "+attemptPassenger+"/5");
                    attemptPassenger++;
                }
                if (attemptPassenger == 4){
                    JOptionPane.showMessageDialog(this , "Multiple incorrect entries , please try again later or click on forgot password" , "ERROR" , JOptionPane.ERROR_MESSAGE);
                }
                if (attemptPassenger == 6){
                    JOptionPane.showMessageDialog(this , "Maximum number of attempts reached" , "ERROR" , JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Couldn't connect to Database , please recheck connection" , "ERROR" , JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_passengerLoginBtnActionPerformed

    private void forgotPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordBtnActionPerformed
        passengerForgotPassword forgot = new passengerForgotPassword();
        forgot.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_forgotPasswordBtnActionPerformed

    private void registerPassengerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPassengerBtnActionPerformed
        passengerRegistration register = new passengerRegistration();
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerPassengerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passengerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgotPasswordBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mouseDrag1;
    private javax.swing.JLabel mouseDrag2;
    private javax.swing.JButton passengerExitBtn;
    private javax.swing.JButton passengerLoginBackBtn;
    private javax.swing.JButton passengerLoginBtn;
    private javax.swing.JButton passengerMinimizeBtn;
    private javax.swing.JPasswordField passengerPasswordInput;
    private javax.swing.JTextField passengerUserInput;
    private javax.swing.JButton registerPassengerBtn;
    // End of variables declaration//GEN-END:variables
}
